# Generated by Django 3.2.3 on 2021-05-31 16:16

import app.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfilelog',
            name='file',
            field=models.FileField(upload_to=app.misc.path_unique_name, validators=[app.misc.file_should_excel], verbose_name='Excel file'),
        ),
    ]
