# Generated by Django 3.2.3 on 2021-06-03 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_adminfilelog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='budgetExpenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('weekly', models.FloatField()),
                ('bi_weekly', models.FloatField()),
                ('monthly', models.FloatField()),
                ('yearly', models.FloatField()),
                ('is_sub_query', models.BooleanField(default=False)),
                ('budget_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.budgetexpenses')),
            ],
        ),
        migrations.CreateModel(
            name='itemsSub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.items')),
            ],
        ),
    ]
